name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-nix:
    name: Cargo test on nix
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        toolchain:
          - 1.68
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: docker version
      - run: cargo test --no-run
      - run: cargo test --no-fail-fast
    timeout-minutes: 20

